### PR TITLE
added support for running pylint with optional --jobs arg

### PR DESCRIPTION
**Pull request by eerac**
@algrs @paulmelnikow @lillekemiker Following up on Martin's suggestion in other PR.

### CODE REVIEW

**Comment by paulmelnikow** [comment]
:+1:

**Comment by eerac** [comment]
@paulmelnikow Oh, I think I just realized that pylint_test needs to be able to take multiple modules as arguments for --jobs to be useful. Do you agree? I'll push an update it a bit

**Comment by eerac** [comment]
@paulmelnikow Actually, it seems like doing what I just said might conflict with previous ways in which this function is being used. Thoughts?

**Comment by eerac** [comment]
maybe I should add a second command?

**Comment by eerac** [comment]
From my most recent commit:

pylint_test now allows you to pass in multiple modules and also ignore multiple modules. Unfortunately this is a breaking change with what we had before as ignoring modules now (necessarily) requires use of the --ignore flag (as is the case with pylint). The reason for this change is that the --jobs flag, which can easily provide a factor of 2 speed up, requires that multiple modules be passed in so they can be listed concurrently

@algrs @paulmelnikow @lillekemiker  I think this is a worthwhile update as it will allow me to modify rake lint yield a factor of 2 speedup (not just on circleci). Are we using the current command with an "ignore" argument? If so we'll need to add an `--ignore` flag

**Comment by algrs** [comment]
I don't know of anywhere that's using the ignore feature... But this is pulled in to repos by version number, so you can bump the version here to `1.1.0` to make it clear that there's a breaking change and repos will still use the older version until they explicitly start asking for the new one.

👍

**Comment by paulmelnikow** [comment]
I don't think we're using ignore anywhere. It seems safe to remove it, and I'd encourage that. This script is pretty complicated, simpler is better is less to maintain.

If it's a breaking change in the calling convention, a semver major bump would be appropriate (`2.0.0`).

👍

**Comment by eerac** [comment]
Ok, I will merge and version bump to 2.0.0 as an indication of the enormous progress we've achieved. For individual repos, would we have to change it in each one or is there a default version in dev-tools I should update?

**Comment by paulmelnikow** [comment]
It's declared in each repo. By pinning the version, we prevent everything from breaking, you can upgrade at your convenience.

If you want, you could update the "important" Python repos...

**Pull request merged**
